// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhxcnadkkojuasdgrcek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeGNuYWRra29qdWFzZGdyY2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjE0MjIsImV4cCI6MjA2NTg5NzQyMn0.PnZXbMKxLfgQWY220BcxQe4w9ZUrGrBkB-1Zi7w5oPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);